project:
  type: website
  output-dir: docs

website:
  title: "Análisis Cuantitativo para Preguntas Sociales"
  description: "Portafolio de proyectos en ciencias sociales"
  
  navbar:
    background: "primary"
    left:
      - href: index.qmd
        text: Inicio
      - href: projects.qmd
        text: Más Proyectos
    right:
      - icon: github
        href: https://github.com/Mayari27
      
  page-footer:
    center: "© 2024 - Hecho con R y Quarto"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
execute:
  warning: false
  message: false